export const FETCH_POST = "POSTS/FETCH_POST";
export const FETCH_POST_SUCCESS = "POSTS/FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "POSTS/FETCH_POST_FAIL";
export const REORDER_POSTS = "POSTS/REORDER_POSTS";
export const TOGGLE_LIKE_POST = "POSTS/TOGGLE_LIKE_POST";
export const DELETE_POST = "POSTS/DELETE_POST";

export const DISABLE_INTERACTION = "APP/DISABLE_INTERACTION";
export const ENABLE_INTERACTION = "APP/ENABLE_INTERACTION";
export const SHOW_WARNING = "APP/SHOW_WARNING";
export const HIDE_WARNING = "APP/HIDE_WARNING";

export const CREATE_TOPIC = "TOPIC/CREATE_TOPIC";
