export const FETCH_POST = "POSTS/FETCH_POST";
export const FETCH_POST_SUCCESS = "POSTS/FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "POSTS/FETCH_POST_FAIL";

export const REORDER_POSTS = "POSTS/REORDER_POSTS";

export const HIDE_WARNING = "POSTS/HIDE_WARNING";

export const LIKE_POST = "POSTS/LIKE_POST";
export const DELETE_POST = "POSTS/DELETE_POST";

export const UNDO = "POSTS/UNDO";
export const REDO = "POSTS/REDO";

export const DISABLE_INTERACTION = "APP/DISABLE_INTERACTION";
export const ENABLE_INTERACTION = "APP/ENABLE_INTERACTION";

// export const DELETE_TOPIC = "THEME/DELETE_TOPIC";
// export const CREATE_TOPIC = "THEME/CREATE_TOPIC";
